version: '2'
services:
  fibapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - 8080
      - 5000
    expose:
      - 8080:8080
      - 5000:5000
    links:
      - redis
  redis:
    image: redis:alpine
